name: Generate Animation

on:
  # Run every 24 hours (can be adjusted based on preference)
  schedule:
    - cron: "0 0 * * *"  # Run at midnight UTC

  # Allow manual triggering
  workflow_dispatch:

  # Run on pushes to the main branch (or desired branch)
  push:
    branches:
      - main        # Change to your target branch

jobs:
  generate:
    permissions:
      contents: write  # Permission to push to the output branch
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Adjust timeout if needed

    steps:
      - uses: actions/checkout@v3  # Checkout repository code

      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.actor }}  # Use the running user's name
          outputs: |  # Define output file paths
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push SVGs to Output Branch (Optional)
        uses: crazy-max/ghaction-github-pages@v3.1.0  # Consider using alternative deployment actions
        if: ${{ github.event_name == 'push' }}  # Only deploy on pushes (optional)
        with:
          target_branch: output  # Change to your desired output branch name
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use a dedicated secret for deployment
